# Generated by Django 5.1.4 on 2025-11-17 09:58

import starstay_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starstay_app', '0002_rename_username_visitor_name_visitor_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('media_file', models.FileField(blank=True, null=True, upload_to=starstay_app.models.showcase_upload_path)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
